---
title: Landano
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  services:
    title: Services
    output: true
    permalink: "/:collection/:path/"
  team:
    title: Team
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: services
  values:
    layout: service
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: team
  values:
    layout: team
- scope:
    path: ''
    type: posts
  values:
    layout: post
    weight: 999
- scope:
    path: images
  values:
    image: true
- scope:
    path: categories
  values:
    permalink: "/category/:basename/"
- scope:
    path: pages
  values:
    permalink: "/:basename/"
baseurl: "/"
url: ''
permalink: pretty
markdown: kramdown
highlighter: rouge
collections_dir: collections
plugins:
- jekyll-environment-variables
- jekyll-paginate
paginate: 6
paginate_path: "/blog/page/:num"
sass:
  style: compact
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- netlify.toml
category_dir: category
colors:
  primary: "#1172ba"
  primary_2: "#08385c"
  primary_text: "#fdfcf9"
  secondary: "#702bf7"
  background: "#ffffff"
  background_2: "#f8f9ff"
  background_3: "#eef2f9"
  text: "#0d042b"
  text_2: "#3b364c"
  primary_dark: "#1172ba"
  primary_2_dark: "#08385c"
  primary_text_dark: "#fdfcf9"
  secondary_dark: "#8215cb"
  background_dark: "#0f0f10"
  background_2_dark: "#1a191c"
  background_3_dark: "#222124"
  text_dark: "#f5f5ec"
  text_2_dark: "#b6c3d6"
fonts:
  google_fonts: https://fonts.googleapis.com/css2?family=Jost&family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro:wght@300;400;700&display=swap
  heading: Jost
  base: Jost
  monospace: Fira Mono
  logo: Lato
logo:
  logo_text: Landano
  logo_image: assets/images/logo/logo.png
  logo_image_mobile: assets/images/logo/logo-mobile.png
  logo_image_invert: assets/images/logo/logo-invert.png
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  logo_image_desktop_height: 60px
  logo_image_desktop_width: 318px
  logo_image_mobile_height: 30px
  logo_image_mobile_width: 34px
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: false
header:
  fixed: true
darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: false
  show_dark_mode_toggle_in_bottom: true
  show_dark_mode_toggle_in_mobile_menu: true
analytics:
  google_analytics_id: G-T4TGVCNL8F
disqus:
  shortname: ''
mailchimp:
  form_action_url: https://zerostatic.us13.list-manage.com/subscribe/post?u=675276692aebec1c007f8156d&amp;id=3e3da720c2
contact_form:
  use_netlify_form: false
  use_hubspot_form: true
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv
menu:
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true
footer:
  enable_footer: true
  footer_title: Landano B.V.
  footer_description: Securing property rights for everyone.
  enable_social_media_icons: true
  enable_contact_details: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: Product
  footer_secondary_menu_title: Company
  footer_tertiary_menu_title: Other
bottom:
  enable_bottom: true
  enable_bottom_menu: true
  copyright_text: "© 2023 Landano B.V."
sidebar:
  enable_sidebar_services: true
  enable_breadcrumbs_services: true
  enable_sidebar_projects: false
  enable_breadcrumbs_projects: true
