backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/uploads" 

collections:
  - name: "blog"
    label: "blog"
    folder: "collections/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list"}




